### ISSUE TITLE
Checklist items for Workshop 2

### ISSUE THREAD

**Issue by mtaromi** [Ahmed-Sadeq-Hussein/Mjukvaruutvekling-grupp-5#18]
Part 1 - OO Design 
- [x] Carry on with your implementation adding more features
- [x] Create few issues on using GRASP which are “closed” with an associated implementation

Part 2 - Using version control software (Git)
- [x] Add a .gitignore file to your project
- [x] #20
- [x] #21
- [x] #22
- [x] Has a branch in conflict with main/master 
- [x] #23
- [x] #24
- [x] Has issues associated with each of your changes.
