### ISSUE TITLE
Checklist items for Workshop 3

### ISSUE THREAD

**Issue by mtaromi** [Ahmed-Sadeq-Hussein/Mjukvaruutvekling-grupp-5#31]
Part 1 - Automated testing part 1 (unit testing)
Add tests to your project. Carry on with the project implementation.

Checklist:

- [x] Has a unit test.
- [x] Has several unit tests of different features and modules.
- [x] Tests are passing on the `master`/`main` branch.
- [x] #38
- [x] README with instructions of how to generate code coverage information for your unit tests
- [x] #72
- [x] If you are using assets found online as part of your project, please explicitly list these on the README.

Part 2 — Continuous Integration (CI) with GitHub actions
Add CI to your project. Carry on with the project implementation.

Checklist:

- [x] Continuous Integration (CI) through GitHub Actions.
- [x] CI checks that your code compiles or parses.
- [x] CI checks that the unit tests are passing.
- [x] master/main is passing / green.
- [x] #51
- [ ] Optional items if you want to walk the extra mile 😁:
  - [ ] (optional) CI produces code coverage information.
  - [ ] (optional) CI performs lint checks.
