### ISSUE TITLE
Lecture 10 checklist

### ISSUE THREAD

**Issue by RamaTech03** [Ahmed-Sadeq-Hussein/Mjukvaruutvekling-grupp-5#43]

**Comment by Baesar** [comment]
Part 1 - Versioning, Releases and Continuous Delivery (CD)
Carry on with your project implementation.  Make your first release v0.1.0 using [Semantic Versioning](https://semver.org/) by creating a git tag v0.1.0.

Checklist:

- [x] Make your first release v0.1.0 by creating a tag through git.
- [] Generate [an artifact](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) through CI.  This can be anything that makes sense to your project: an executable file, a code coverage report, an installer for the built version, etc.
- [] (Optional) (if your project is a "desktop" project, you may choose to do this if you like) When a commit is tagged with a version (v0.1.2), a release artifact is generated: this may be a simple executable or an installer
- [ ] (Optional) (if your project is a "web" project, you may choose to do this if you like) When a commit is tagged with a version (v0.1.2), the application is deployed on a (testing) server

Part 2 — DevOps
Carry on with your project implementation using the techniques from this and previous lectures.


Checklist:

- [x] Create an issue titled "Lecture 10 checklist" to track these checklist items
- [] Define a few project goals for the upcoming weeks, create them as issues, list them in the "Lecture 10 checklist" issue.
- [x] Make a new release following Semantic Versioning rules.
