### ISSUE TITLE
Lecture 11 checklist

### ISSUE THREAD

**Issue by RamaTech03** [Ahmed-Sadeq-Hussein/Mjukvaruutvekling-grupp-5#44]

**Comment by Baesar** [comment]
Part 1 — Automated testing part 2
Carry on with your project implementation using the techniques from this and previous lectures.

 - [ ] create an issue titled "Lecture 11 checklist" to track these checklist items
 - [ ] each student has created at least two to five unit tests with matching PRs and code review
 - [ ] project has at least one of the following types of tests:
  - [ ] Integration tests
  - [ ] Nonfunctional tests (e.g.: performance, capacity)
  - [ ] [Optional] Property tests
 - [ ] code coverage of tests is increased by at least 20%.  List the "starting" and "ending" commits in the "Lecture 11 checklist" issue with the achieved percentage increase.
 - [ ] main is still passing/green. (and should be always from now on!)

**Comment by Baesar** [comment]
each student has created at least two to five unit tests with matching PRs and code review

commits:
a9ebdb7
079da0c
aa7dcd0

**Comment by RamaTech03** [comment]
Project has at least one of the following types of tests:

-Added an integration test to test the integration between controller and model
commits: 
1d7d4d1
9e19df6

**Comment by Baesar** [comment]
Code coverage of tests is increased by at least 20%. List the "starting" and "ending" commits in the "Lecture 11 checklist" issue with the achieved percentage increase.

Line coverage of starting commit: 24.4%
Line coverage of ending commit: 31.3%

That is an increase of 28,3%

Starting commit: b128d20
Ending commit: 4b58f70
